site_name: 2020_5AI_Team4

nav:
    - 'Project charter': 'Project_Character.md'
    - 'Software Requirements Specification Plan': 'Software_Requirements_Specification.md'
    - 'Software Project Management Plan': 'Software_Project_Management_Plan.md'
    - 'Release Plan': 'Release_Plan.md'
    - 'Test Case Specification': 'Test_Case_Specification.md'
    - 'System Requirements Documentation': 'System_Requirements_Documentation.md'
    - 'Memo of Understanding': 'Memo_of_Understanding.md'
    - 'Iteration Plan': 'Iteration_Plan.md'
    - 'Architecture Design & Coding Standards': 'Architecture_Design_CodingStandards.md'
    - 'Test Plan': 'Test_Plan.md'
    - 'Project Success Criteria': 'Project_Success_Criteria.md'
    - 'User Guide': 'User_Guide.md'

    - 'PDF Business Model Canvas': 'Business_Model_Canvas.pdf'
    - 'PDF Project Model Canvas': 'Project_Model_Canvas.pdf'
    - 'PDF Project Character': 'Project_Character.pdf'
    - 'PDF Release Plan': 'Release_Plan.pdf'
    - 'PDF Software Project Management Plan': 'Software_Project_Management_Plan.pdf'
    - 'PDF Software Requirements Specification': 'Software_Requirements_Specification.pdf'
    - 'PDF Test Case Specification': 'Test_Case_Specification.pdf'
    - 'PDF System Requirements Documentation': 'System_Requirements_Documentation.pdf'
    - 'PDF Memo of Understanding': 'Memo_of_Understanding.pdf'
    - 'PDF Iteration Plan': 'Iteration_Plan.pdf'
    - 'PDF Architecture Design & Coding Standards': 'Architecture_Design_CodingStandards.pdf'
    - 'PDF Test Plan': 'Test_Plan.pdf'
    - 'PDF Project Success Criteria': 'Project_Success_Criteria.pdf'
    - 'PDF User Guide': 'User_Guide.pdf'


theme:
    name: readthedocs
