site_name: 2020_5AI_Team4

nav:
    - 'Project charter': 'Project_Character.md'
    - 'Software Requirements Specification Plan': 'Software_Requirements_Specification.md'
    - 'Software Project Management Plan': 'Software_Project_Management_Plan.md'
    - 'Release Plan': 'Release_Plan.md'
    - 'Test_Case_Specification': 'Test_Case_Specification.md'


theme:
    name: readthedocs
